#!/bin/bash
# httrack --near "https://froggy.lbl.gov/images/math/" '+*' -O "./mirror/math/"
# httrack --near "https://froggy.lbl.gov/images/orange/" '+*' -O "./mirror/orange"
# httrack --near "https://froggy.lbl.gov/images/orange/data/" '+*' -O "./mirror/orange/data"
# httrack --near "https://froggy.lbl.gov/images/pumpkin/" '+*' -O "./mirror/pumpkin/"
# httrack --near "https://froggy.lbl.gov/images/rat/" '+*' -O "./mirror/rat/"
# httrack --near "https://froggy.lbl.gov/images/tomato/" '+*' -O "./mirror/tomato/"
# httrack --near "https://froggy.lbl.gov/images/tomato/data/" '+*' -O "./mirror/tomato/data"
# httrack --near "https://froggy.lbl.gov/images/virtual/" '+*' -O "./mirror/virtual/"
# httrack --near "https://froggy.lbl.gov/images/virtual/organs/" '+*' -O "./mirror/virtual/organs/"
# httrack --near "https://froggy.lbl.gov/images/whole.frog/" '+*' -O "./mirror/whole.frog/"
# httrack --near "https://froggy.lbl.gov/images/whole.frog/data/" '+*' -O "./mirror/whole.frog/data"
# httrack --near "https://froggy.lbl.gov/images/whole.frog/data/MRI/" '+*' -O "./mirror/whole.frog/data/MRI/"
# httrack --near "https://froggy.lbl.gov/images/whole.frog/data/MRI/tiff/" '+*' -O "./mirror/whole.frog/data/MRI/tiff/"
# httrack --near "https://froggy.lbl.gov/images/whole.frog/data/masks/" '+*' -O "./mirror/whole.frog/data/masks/"
# httrack --near "https://froggy.lbl.gov/images/whole.frog/data/masks/animations/" '+*' -O "./mirror/whole.frog/data/masks/animations/"
# httrack --near "https://froggy.lbl.gov/images/whole.frog/data/masks/tiff/" '+*' -O "./mirror/whole.frog/data/masks/tiff/"
# httrack --near "https://froggy.lbl.gov/images/whole.frog/data/tiff/" '+*' -O "./mirror/whole.frog/data/tiff/"

wget --recursive --no-clobber --domains=froggy.lbl.gov https://froggy.lbl.gov/
